[tool.mypy]
# Global mypy configurations can be added here
exclude = ["repos", "datasets"]

[[tool.mypy.overrides]]
module = "transformers.*"
ignore_missing_imports = true
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "huggingface_hub.*"
ignore_missing_imports = true
follow_imports = "skip"

[tool.ruff]
exclude = ["repos", "datasets"]

[tool.ruff.lint]
# https://docs.astral.sh/ruff/settings/#lint_ignore-init-module-imports
ignore-init-module-imports = true