[tool.poetry]
name = "thesis-app"
version = "0.1.0"
description = ""
authors = ["Daniel Engbert <end1@umbc.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
transformers = "^4.37.2"


[tool.poetry.group.dev.dependencies]
black = "^24.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
