version: "3.8"
name: thesis

services:
  backend:
    platform: ${PROD_PLATFORM}
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      target: prod
    environment:
      - DB_PASS=${DB_PASS}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}

  nginx:
    platform: ${PROD_PLATFORM}
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
      target: nginx_prod
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - env=PROD
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/

    command: nginx -g 'daemon off;'

  db:
    platform: ${PROD_PLATFORM}
    image: postgres:14
    ports:
      # using "local loopback interface" so UFW rules are respected
      - 127.0.0.1:5400:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ${VOLUMES_DIR}/db:/var/lib/postgresql/data
      - ${VOLUMES_DIR}/backups:/backups