name: thesis

services:
  backend:
    platform: ${PROD_PLATFORM}
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - .env
    environment:
      ENV: PRD
    volumes:
      - ${VOLUMES_DIR}/files:/files

  jobs:
    platform: ${PROD_PLATFORM}
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - .env
    environment:
      ENV: PRD
    volumes:
      - ${VOLUMES_DIR}/files:/files
    command: ./jobRunner.py

  nginx:
    platform: ${PROD_PLATFORM}
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
      target: nginx_prod
    ports:
      - 443:443
      - 80:80
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - env=PROD
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/

    command: nginx -g 'daemon off;'

  db:
    platform: ${PROD_PLATFORM}
    image: postgres:14
    ports:
      # using "local loopback interface" so UFW rules are respected
      - 127.0.0.1:5400:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ${VOLUMES_DIR}/db:/var/lib/postgresql/data
      - ${VOLUMES_DIR}/backups:/backups