version: "3.8"
name: thesis_dev

services:
  backend:
    platform: ${LOCAL_PLATFORM}
    build:
      target: dev
    volumes:
      - ../backend/:/backend/
    environment:
      - env=DEV
    ports:
      - 127.0.0.1:8000:8000
    # command: "bash -c 'echo sleeping && sleep infinity'"
    command: "bash -c './manageDB.py --maybe-migrate && ./launch_dev.py'"

  nginx:
    platform: ${LOCAL_PLATFORM}
    build:
      target: react_dev
    environment:
      - DEV_HOST_PORT=2222
    ports:
      - 127.0.0.1:2222:2222
    volumes:
      - ../frontend/:/frontend/
    # command: "sh -c 'echo sleeping && sleep infinity'"
    command: "sh -c 'yarn && yarn start'"

  db:
    platform: ${LOCAL_PLATFORM}
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}