"""add User_name_sub

Revision ID: b5d6d7937f3b
Revises: d0878fab613f
Create Date: 2024-05-04 18:10:21.096671+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5d6d7937f3b"
down_revision: Union[str, None] = "d0878fab613f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(), nullable=False))
    op.add_column("user", sa.Column("sub", sa.String(), nullable=False))
    op.create_unique_constraint("uq_user_sub", "user", ["sub"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_sub", "user", type_="unique")
    op.drop_column("user", "sub")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
