"""jobs and scorable assignments

Revision ID: 03d7881322c8
Revises: 4403fa76e1de
Create Date: 2024-05-25 11:17:48.689584+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03d7881322c8"
down_revision: Union[str, None] = "4403fa76e1de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("job_type", sa.Enum("AI_FEEDBACK", name="jobtype"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.add_column("assignment", sa.Column("scorable", sa.Boolean(), nullable=True))
    op.execute("UPDATE assignment SET scorable = FALSE")
    op.alter_column("assignment", "scorable", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment", "scorable")
    op.drop_table("job")
    op.execute("DROP TYPE jobtype")
    op.execute("DROP TYPE jobstatus")
    # ### end Alembic commands ###
