name: frontend-test

on:
  push:
    paths:
      - "frontend/**"

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Yarn Install
        run: |
          yarn global add nx@latest
          yarn install --frozen-lock

      - name: checks.sh
        run: bash ./checks.sh